BEGIN;

ALTER TABLE frota_veiculos
  ADD COLUMN IF NOT EXISTS renavam VARCHAR(11),
  ADD COLUMN IF NOT EXISTS chassi VARCHAR(17),
  ADD COLUMN IF NOT EXISTS combustivel VARCHAR(30),
  ADD COLUMN IF NOT EXISTS observacoes TEXT;

COMMIT;
