/** Substituído no start pelo entrypoint (WPP_SECRET_KEY do .env). */
export default {
  secretKey: '__WPP_SECRET_KEY__',
  host: 'http://localhost',
  port: '21465',
  deviceName: 'Meridian',
  poweredBy: 'WPPConnect-Server',
  startAllSession: false,
  tokenStoreType: 'file',
  maxListeners: 15,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: 'http://app:3007/auditoria/api/wpp/webhook',
    autoDownload: false,
    uploadS3: false,
    readMessage: true,
    allUnreadOnStart: false,
    listenAcks: false,
    onPresenceChanged: false,
    onParticipantsChanged: false,
    onReactionMessage: false,
    onPollResponse: false,
    onRevokedMessage: false,
    onLabelUpdated: false,
    onSelfMessage: false,
    ignore: [
      'status@broadcast',
      'onpresencechanged',
      'onack',
      'onrevokedmessage',
      'status-find',
      'onparticipantschanged',
      'onreactionmessage',
      'onpollresponse',
      'onupdatelabel',
    ],
  },
  websocket: {
    autoDownload: false,
  },
  log: {
    level: 'warn',
    logger: ['console', 'file'],
  },
  createOptions: {
    autoClose: 0,
    browserArgs: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--disable-extensions',
      '--no-first-run',
      '--ignore-certificate-errors',
    ],
  },
};
